name: Build & Push Cart Service

on:
  push:
    branches:
      - master  # Or 'main' if thatâ€™s your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Cart JAR
        run: |
          cd backend/cart
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          ls -l target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Cart Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/cart
          file: ./backend/cart/Dockerfile
          push: true
          tags: harshitha2802/cart-service:latest
